# Generated by Django 3.2 on 2022-02-18 14:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, verbose_name='actif')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('required_age', models.PositiveIntegerField(verbose_name='âge requis')),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(default=0, verbose_name='prix')),
            ],
            options={
                'verbose_name': 'activité physique',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, verbose_name='actif')),
                ('last_name', models.CharField(max_length=200, verbose_name='nom')),
                ('first_name', models.CharField(max_length=200, verbose_name='prénoms')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(15)])),
                ('phone', models.CharField(max_length=20, verbose_name='téléphone')),
            ],
            options={
                'verbose_name': 'client',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, verbose_name='actif')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.activity', verbose_name='activité physique')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer', verbose_name='client')),
            ],
            options={
                'verbose_name': 'inscription',
                'db_table': 'inscription',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='activities',
            field=models.ManyToManyField(through='api.Registration', to='api.Activity'),
        ),
    ]
