# Generated by Django 3.2 on 2022-02-18 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='required_age',
            new_name='age_requis',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='date_add',
            new_name='date_ajout',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='date_update',
            new_name='date_modification',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='price',
            new_name='prix',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='activities',
            new_name='activites',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date_add',
            new_name='date_ajout',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='date_update',
            new_name='date_modification',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='prenom',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='tel',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='activity',
            new_name='activite',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='customer',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='date',
            new_name='date_ajout',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='date_add',
            new_name='date_inscription',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='date_update',
            new_name='date_modification',
        ),
    ]
