# Generated by Django 3.2 on 2022-02-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_registration_registration_unique'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activite',
        ),
    ]
